### ISSUE TITLE
False positive rule: INDICATOR_SUSPICIOUS_EXE_References_CryptoWallets

### ISSUE THREAD

**Issue by ipetrovic11** [ditekshen/detection#10]
After scanning our [Electron](https://electronjs.org/) based application on virus total, we got that it's matching this crowdsourced rule: [INDICATOR_SUSPICIOUS_EXE_References_CryptoWallets](https://github.com/ditekshen/detection/blob/acd2c4e685687d35cc7e450781a1562aee8f2dca/yara/indicator_suspicious.yar#L474)

The issue here is huge since many regular applications like Slack, Figma, etc. are based on Electron as well, so this rule should exclude [$app35 = "Electron" nocase ascii wide](https://github.com/ditekshen/detection/blob/acd2c4e685687d35cc7e450781a1562aee8f2dca/yara/indicator_suspicious.yar#L513) since it is not the same as the next line ElectrumLTC which actually is Litecoin client: https://electrum-ltc.org/

**Comment by ditekshen** [comment]
Can you provide a hash or file? Should make life easier to troubleshoot.

**Comment by ipetrovic11** [comment]
https://www.virustotal.com/gui/file/0c13da0547c022a3f1e4c3b7568782998ea84ceb079daeb4f450258e5679c4b8
<img width="1275" alt="Screen Shot 2022-09-27 at 8 42 06 PM" src="https://user-images.githubusercontent.com/3995534/192609742-787836ee-9aa9-46ac-bc1c-69cf56af0fc3.png">

**Comment by McAlm** [comment]
I have the same issue with this hash: https://www.virustotal.com/gui/file/3c45b7cd83ea3e3216f7dc6b3d422bdeaf87b70c80ff38ab94a070cd7fc26937
The scanned application is open source based on Electron, too: 
https://github.com/camunda/camunda-modeler

**Comment by inikishev** [comment]
I had this with trillium, joplin

**Comment by Aemony** [comment]
This is also a problem for most apps that interfaces or otherwise make use of gaming related platforms due to the inclusion of gaming platforms for some reason among the ruleset:

```
        $app26 = "Riot Games\\" nocase ascii wide
        $app28 = "Battle.net\\" nocase ascii wide
        $app29 = "Steam\\" nocase ascii wide
        $app30 = "Valve\\Steam\\" nocase ascii wide
```

*Any* application that has functionality related to one of the above gaming platforms matches the rule -- even Valve's own Steam client itself: https://www.virustotal.com/gui/file/73fe99caf7f49a20b6319b1fd0212dd105650bad2dd03101bc28a90edeb14b38

In our case, https://special-k.info/, we provide a game launcher feature that populates installed Steam games and shows when they're running or closed -- which requires reading Steam's local VDF files or registry key as that's where data is stored in...

I am not sure what the purpose of these patters are intended for, as they have nothing to do with the stated reason of identifying cryptocurrency mining wallets or apps as neither Riot Games' launcher, Battle.net, nor Steam is used for either.

**Comment by GorlikItsMe** [comment]
```
        $app34 = "DigitalCoin" nocase ascii wide
        $app35 = "Electron" nocase ascii wide
        $app36 = "ElectrumLTC" nocase ascii wide
```
Why is there `Electron`? Because of it my electron-based app is flagged.

**Comment by ditekshen** [comment]
Rules has been disabled until further review. Thanks.
